-- Schema for DecoraTV
-- Focus: Single tenant, English language, Professional enmarcado simulator

-- 1. Materials Table (Frames, Liners, arts)
CREATE TABLE IF NOT EXISTS materials (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL, -- 'frame', 'liner', 'art'
    name TEXT NOT NULL,
    image_path TEXT NOT NULL,
    artist TEXT DEFAULT NULL, -- only for 'art'
    group_name TEXT DEFAULT 'General',
    internal_id TEXT UNIQUE NOT NULL, -- The ID from the user (campo ID)
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Quotes / Orders Table
CREATE TABLE IF NOT EXISTS quotes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_name TEXT NOT NULL,
    customer_last_name TEXT,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    selection_json TEXT NOT NULL, -- Stores IDs and details of the design
    status TEXT DEFAULT 'pending', -- 'pending', 'contacted', 'completed'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. Settings Table (SMTP and Global Config)
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 4. Admin Users
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Initial default settings
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_host', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_port', '587');
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_user', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_pass', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_from_email', '');
INSERT OR IGNORE INTO settings (key, value) VALUES ('smtp_from_name', 'DecoraTV Quotes');
INSERT OR IGNORE INTO settings (key, value) VALUES ('site_name', 'DecoraTV Simulator');
INSERT OR IGNORE INTO settings (key, value) VALUES ('admin_email', 'admin@decoratv.com');

-- Default Admin (Change password on first login)
-- Default password: 'admin' (password_hash for 'admin' will be generated by script)
